title: Cognitive offloading
description: Emptying the mind, one article at a time
author: Jeremy Lemaire
email: jeremy.lemaire (@) gmail.com
theme: no-style-please
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
